name: App Containerization
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push_to_DockerHub:
    name: Build and Push Image to DockerHub
    runs-on: ubuntu-latest
    #needs: []

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: grandthefthotel
          password: ${{ secrets.API_KEY }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: grandthefthotel/grande_management:latest

